import type { CategoryColorKey } from '../../theme/tokens';
import type { SortMode } from './logic/sorting';

export const colorNames: Record<CategoryColorKey, string> = {
  rose: '분홍',
  terracotta: '살구',
  blue: '하늘',
  green: '연두',
  purple: '라벤더',
  amber: '레몬',
  teal: '민트',
  gray: '회색',
};

export const ddayStrings = {
  appTitle: '내곁의 디데이',
  addTitle: '디데이 추가',
  editTitle: '디데이 수정',
  add: '추가',
  filterAll: '전체',
  today: (date: string) => `오늘 · ${date}`,
  countSummary: (count: number) => `디데이 ${count}개`,
  emptyCategory: '이 분류에는 아직 디데이가 없어요.',
  fieldCategory: '분류',
  manageCategories: '편집',
  categoriesTitle: '분류 관리',
  categoryNamePlaceholder: '새 분류 이름',
  categoryColor: '색상',
  categoryAdd: '분류 추가',
  categoryLimit: (max: number) => `분류는 ${max}개까지 만들 수 있어요.`,
  categoryNameErrors: {
    empty: '이름을 입력해 주세요.',
    'too-long': (max: number) => `이름은 ${max}자 이내로 입력해 주세요.`,
    duplicate: '같은 이름의 분류가 이미 있어요.',
  },
  categoryItemCount: (count: number) => `디데이 ${count}개`,
  categoryDeleteTitle: (name: string) => `'${name}' 분류를 삭제할까요?`,
  categoryDeleteMove: (count: number, fallback: string) =>
    `이 분류의 디데이 ${count}개는 '${fallback}' 분류로 옮겨져요.`,
  categoryDeleteEmpty: '이 분류에는 디데이가 없어요.',
  categoryDeleteLast: '분류는 하나 이상 있어야 해요.',
  categoryListTitle: '내 분류',
  sortTitle: '정렬',
  sortLabels: {
    upcoming: '가까운 순',
    manual: '직접 정렬',
    recent: '최근 추가 순',
    title: '이름순',
  } satisfies Record<SortMode, string>,
  sortButton: (label: string) => `${label} ▾`,
  sortManualHint: '카드 왼쪽 위 막대를 끌거나 카드를 길게 눌러 순서를 바꿔요.',
  moveUp: '위로 옮기기',
  moveDown: '아래로 옮기기',
  reorderFailed: '순서를 저장하지 못했어요',
  sectionBasic: '기본 정보',
  sectionRepeat: '기념일',
  sectionNotification: '알림',
  datePickerTitle: '날짜 선택',
  lunarPickerTitle: '음력 날짜 선택',
  leapMonth: (month: number) => `윤${month}월`,
  plainMonth: (month: number) => `평${month}월`,
  calendarSolar: '양력',
  calendarLunar: '음력',
  solarEquivalent: (date: string) => `양력 ${date}`,
  lunarOutOfRange: '음력은 2050년까지만 지원해요.',
  datePickerToday: '오늘',
  datePickerConfirm: '확인',
  year: '년',
  month: '월',
  day: '일',
  emptyTitle: '소중한 날을 곁에 두세요',
  emptyBody: '기념일, 생일, 시험일처럼 기다리는 날을 추가하면 남은 날과 함께한 날을 세어 드릴게요.',
  emptyAction: '첫 디데이 만들기',
  loadErrorTitle: '디데이를 불러오지 못했어요',
  loadErrorBody: '저장된 기록은 지우지 않았어요. 다시 시도해도 계속되면 앱을 업데이트해 주세요.',
  retry: '다시 시도',
  notificationBlocked:
    '알림이 꺼져 있어 중요한 날을 알려 드릴 수 없어요. 휴대폰 설정에서 알림을 허용해 주세요.',
  repeatBadge: '매년',
  dayCount: (count: number) => `${count.toLocaleString()}일째`,
  fieldTitle: '이름',
  fieldTitlePlaceholder: '예: 우리 처음 만난 날, 엄마 생신',
  fieldDate: '날짜',
  fieldRepeat: '매년 반복',
  fieldRepeatHint: '생일·기념일처럼 매년 돌아오는 날',
  fieldMilestones: '100일 단위 기념일',
  fieldMilestonesHint: '사귄 날처럼 함께한 날을 세는 디데이에 좋아요. 100일, 200일…을 챙겨 드려요.',
  milestonesPending: '기준 날짜가 지나면 100일 단위 기념일을 보여 드려요.',
  nextMilestone: (dayCount: number, label: string) =>
    `다음 기념일 ${dayCount.toLocaleString()}일 · ${label}`,
  fieldNotifyOnDay: '당일 알림',
  fieldNotifyBefore: '미리 알림',
  notifyBeforeNone: '없음',
  notifyBeforeOption: (days: number) => `${days}일 전`,
  notifySummaryOff: '알림을 켜 두면 중요한 날을 잊지 않게 알려 드려요.',
  // Android는 배터리 절약을 위해 정확한 시각이 아닌 1시간 안쪽으로 묶어 보낸다.
  notifySummaryOn: (when: string, hour: number) => `${when} 오전 ${hour}시쯤 알려 드릴게요.`,
  notifyWhenOnDay: '당일',
  notifyWhenBoth: (days: number) => `${days}일 전과 당일`,
  notifyDetailNudge: '알림을 켜 두면 이날을 잊지 않게 알려 드려요. 수정에서 켤 수 있어요.',
  notificationBodyOnDay: '오늘이 바로 그날이에요. 잊지 말고 챙겨 주세요!',
  notificationBodyBefore: (days: number) => `${days}일 남았어요. 미리 준비해 볼까요?`,
  save: '저장',
  saving: '저장 중…',
  edit: '수정',
  share: '공유하기',
  sharing: '이미지 만드는 중…',
  shareTitle: '공유 카드',
  shareHint: '카카오톡, 인스타그램 등으로 보내거나 저장할 수 있어요.',
  shareUnavailable: '이 기기에서는 공유할 수 없어요.',
  shareFailed: '공유하지 못했어요',
  delete: '삭제',
  cancel: '취소',
  titleRequired: '이름을 입력해 주세요.',
  titleTooLong: (max: number) => `이름은 ${max}자 이내로 입력해 주세요.`,
  saveFailed: '저장하지 못했어요',
  deleteConfirmTitle: '디데이를 삭제할까요?',
  deleteConfirmBody: '삭제한 디데이와 알림은 되돌릴 수 없어요.',
  deleteFailed: '삭제하지 못했어요',
  permissionDeniedTitle: '알림 권한이 필요해요',
  permissionDeniedBody:
    '디데이는 저장했어요. 중요한 날 알림을 받으려면 휴대폰 설정에서 알림을 허용해 주세요.',
  notFound: '디데이를 찾을 수 없어요.',
  milestonesTitle: '100일 단위 기념일',
  milestoneLatest: '최근 기념일',
  milestoneLabel: (dayCount: number) => `${dayCount.toLocaleString()}일`,
  baseDate: '기준 날짜',
  targetDate: '다가오는 날짜',
  notifications: '알림',
  notificationsOff: '꺼짐',
} as const;
