export const ddayStrings = {
  appTitle: '내곁의 디데이',
  addTitle: '디데이 추가',
  editTitle: '디데이 수정',
  detailTitle: '디데이',
  add: '추가',
  emptyTitle: '아직 디데이가 없어요',
  emptyBody: '기다리는 날이나 기념하고 싶은 날을 추가해 보세요.',
  emptyAction: '첫 디데이 추가하기',
  loadErrorTitle: '디데이를 불러오지 못했어요',
  loadErrorBody: '저장된 기록은 지우지 않았어요. 다시 시도해도 계속되면 앱을 업데이트해 주세요.',
  retry: '다시 시도',
  notificationBlocked:
    '알림 권한이 꺼져 있어 알림을 보낼 수 없어요. 설정에서 알림을 허용해 주세요.',
  repeatBadge: '매년',
  dayCount: (count: number) => `${count.toLocaleString()}일째`,
  fieldTitle: '이름',
  fieldTitlePlaceholder: '예: 우리 만난 날, 시험일',
  fieldDate: '날짜',
  fieldRepeat: '매년 반복',
  fieldRepeatHint: '생일·기념일처럼 매년 돌아오는 날',
  fieldNotifyOnDay: '당일 알림',
  fieldNotifyBefore: '미리 알림',
  notifyBeforeNone: '없음',
  notifyBeforeOption: (days: number) => `${days}일 전`,
  notifyTimeHint: (hour: number) => `알림은 오전 ${hour}시에 와요.`,
  save: '저장',
  saving: '저장 중…',
  edit: '수정',
  delete: '삭제',
  cancel: '취소',
  titleRequired: '이름을 입력해 주세요.',
  titleTooLong: (max: number) => `이름은 ${max}자 이내로 입력해 주세요.`,
  saveFailed: '저장하지 못했어요',
  deleteConfirmTitle: '디데이를 삭제할까요?',
  deleteConfirmBody: '삭제한 디데이와 알림은 되돌릴 수 없어요.',
  deleteFailed: '삭제하지 못했어요',
  permissionDeniedTitle: '알림 권한이 필요해요',
  permissionDeniedBody: '디데이는 저장했어요. 알림을 받으려면 설정에서 알림을 허용해 주세요.',
  notFound: '디데이를 찾을 수 없어요.',
  milestonesTitle: '100일 단위 기념일',
  milestoneLatest: '최근 기념일',
  milestoneLabel: (dayCount: number) => `${dayCount.toLocaleString()}일`,
  baseDate: '기준 날짜',
  targetDate: '다가오는 날짜',
  notifications: '알림',
  notificationsOff: '꺼짐',
} as const;
