import type { ThemePreference } from './themePreference';

export const settingsStrings = {
  title: '설정',
  openSettings: '설정 열기',
  themeSection: '화면 모드',
  themeOptions: {
    system: '시스템 설정 따르기',
    light: '라이트',
    dark: '다크',
  } satisfies Record<ThemePreference, string>,
  themeSystemHint: '휴대폰의 라이트·다크 설정에 맞춰 자동으로 바뀌어요.',
  categorySection: '분류',
  manageCategories: '분류 관리',
  proSection: 'Pro',
  proTitle: 'Pro로 업그레이드',
  proBody: '한 번 구매로 평생 써요.\n· 광고 제거\n· 홈 화면 위젯',
  proBuy: (price: string) => `${price}에 Pro 구매`,
  proBuying: '결제 진행 중…',
  proUnavailable: '지금은 구매할 수 없어요. 잠시 후 다시 시도해 주세요.',
  proActive:
    'Pro 사용 중이에요. 고마워요!\n홈 화면 빈 곳을 길게 눌러 위젯 → 내곁의 디데이를 추가해 보세요.',
  proRestore: '구매 복원',
  proRestored: '구매 내역을 복원했어요.',
  proNothingToRestore: '복원할 구매 내역이 없어요.',
  proFailed: '결제하지 못했어요',
  backupSection: '백업',
  backupExport: '백업 파일 내보내기',
  backupImport: '백업 파일 불러오기',
  backupHint:
    '디데이는 이 폰에만 저장돼요. 폰을 바꾸기 전에 백업 파일을 카카오톡 나와의 채팅이나 드라이브에 보관해 두세요.',
  backupShareTitle: '내곁의 디데이 백업',
  backupFailed: '백업하지 못했어요',
  restoreFailed: '불러오지 못했어요',
  restoreInvalid: '내곁의 디데이 백업 파일이 아니거나 파일이 손상됐어요.',
  restoreNewer: '더 새로운 버전의 앱에서 만든 백업이에요. 앱을 업데이트한 뒤 다시 시도해 주세요.',
  restoreConfirmTitle: '백업을 불러올까요?',
  restoreConfirmBody: (items: number, categories: number) =>
    `백업에 디데이 ${items}개, 분류 ${categories}개가 있어요.\n\n합치기: 지금 기록은 그대로 두고 없는 디데이만 더해요.\n바꾸기: 지금 기록을 백업 내용으로 모두 바꿔요.`,
  restoreMerge: '합치기',
  restoreReplace: '바꾸기',
  restoreMerged: (added: number) =>
    added > 0 ? `디데이 ${added}개를 불러왔어요.` : '새로 더할 디데이가 없어요.',
  restoreReplaced: '백업 내용으로 바꿨어요.',
  cancel: '취소',
  privacySection: '개인정보',
  adPrivacyOptions: '광고 개인정보 설정',
  saveFailed: '설정을 저장하지 못했어요',
  devSection: '개발용 (개발 빌드에서만 보임)',
  devTestNotification: '10초 뒤 테스트 알림',
  devScheduledList: '예약된 알림 보기',
  devPinWidget: '위젯을 홈 화면에 추가',
  devWidgetPreview: '위젯 미리보기 이미지 화면',
  devPinUnsupported: '이 런처는 위젯 추가 요청을 지원하지 않아요.',
  devScheduledCount: (count: number) => `예약된 알림 ${count}개`,
} as const;
